spring:
  profiles:
    active:
      - dev

server:
  servlet:
    context-path: /btp

app:
  api-prefix: /api  # 設定 API 路徑前綴

  twse-urls:
    stock-info: "https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL"
    stock-data: "https://www.twse.com.tw/exchangeReport/STOCK_DAY"
    taiex-data: "https://www.twse.com.tw/en/indicesReport/MI_5MINS_HIST"

