spring:
  profiles:
    active:
      - dev

server:
  servlet:
    context-path: /btp/api

app:
  twse-urls:
    stock-info: "https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL"
    stock-data: "https://www.twse.com.tw/exchangeReport/STOCK_DAY"
    taiex-data: "https://www.twse.com.tw/en/indicesReport/MI_5MINS_HIST"

